{"uuid": "bdddb394-70db-4df5-b2f7-96ece64d7569", "children": ["729cf4f6-8037-4aa4-9f5c-ce51044353d7"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'testfailed'\n", "trace": "  File \"c:\\users\\matias\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\matias\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\matias\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Matias\\PycharmProjects\\selenium_projekt_wlasny1\\page_object_pattern\\tests\\conftest.py\", line 14, in setup\n    before_failed = request.session.testfailed\n"}, "start": 1615404258192, "stop": 1615404259572}], "start": 1615404258192, "stop": 1615404259708}